#!/usr/bin/env bash
# Behaviour tests for the hardware seam: the tracked placeholder
# hardware-configuration.nix, and lib/hardware-config.sh, which is what turns it
# into a real machine's generated description.
#
# Every case runs the real, unmodified library against a scratch copy of the
# file, with a fake generator that prints a canned hardware description instead
# of inspecting a machine. Nothing here runs nixos-generate-config, needs Linux,
# or touches the repository's own hardware-configuration.nix.
#
# Why this file exists at all: replacing that file is the one step in this repo
# that can destroy something no amount of re-running gets back. A machine's
# generated hardware description took a reinstall to produce, and a truncated
# one is a machine that cannot find its own root filesystem.
#
# Coverage:
# - the file the repository tracks is the placeholder, and it carries the
#   sentinel that says so;
# - a placeholder is replaced without asking;
# - a real, already-generated file is kept unless the answer is an explicit yes;
# - a generator that fails leaves the existing file byte-for-byte untouched;
# - a generator that prints no root filesystem is refused the same way.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

dotfiles_test_parse_args "$@"

TMP_ROOT=$(dotfiles_test_tmproot dotfiles-hardware)

# shellcheck source=lib/hardware-config.sh
. "$ROOT/lib/hardware-config.sh"

# A plausible generated description. Only the root filesystem line matters to
# the library; the rest is here so the fixture reads like the real output.
GENERATED='# Do not modify this file! It was generated by nixos-generate-config.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" ];
  boot.kernelModules = [ "kvm-amd" ];
  fileSystems."/" = { device = "/dev/disk/by-uuid/deadbeef"; fsType = "ext4"; };
  swapDevices = [ ];
}'

# A scratch directory holding one hardware-configuration.nix, plus a generator
# under our control. Echoes the directory.
#   $1 what the file starts as: "placeholder", "real", or "absent"
make_case() {
  local kind=$1 dir
  dir=$(mktemp -d "$TMP_ROOT/case.XXXXXX") || fail "could not create a case directory"
  case $dir in
    "$TMP_ROOT"/*) [ -d "$dir" ] || fail "case directory $dir was not created" ;;
    *) fail "case path escaped the test temp root: '$dir'" ;;
  esac
  case $kind in
    placeholder) cp "$ROOT/hardware-configuration.nix" "$dir/hardware-configuration.nix" ;;
    real) printf '%s\n' "$GENERATED" >"$dir/hardware-configuration.nix" ;;
    absent) : ;;
    *) fail "unknown case kind: $kind" ;;
  esac
  printf '%s\n' "$dir"
}

# Install a fake generator as an executable file in the case directory and echo
# its path. A file, not a command line: HARDWARE_CONFIG_CMD is expanded unquoted
# by the library - it is a command line, not a filename - so anything with a
# quoted argument in it would be re-split by the shell rather than passed
# through. A single-word path sidesteps that entirely.
#   $1 case directory, $2 the script body
make_generator() {
  local dir=$1 body=$2 path="$1/generator"
  {
    printf '#!/bin/sh\n'
    printf '%s\n' "$body"
  } >"$path"
  chmod +x "$path"
  printf '%s\n' "$path"
}

# Run hardware_config_apply in a subshell, so a case's HARDWARE_CONFIG_CMD and
# stdin cannot leak into the next one.
#   $1 case directory, $2 generator path, $3 stdin to feed
# Writes combined output to <dir>/out and echoes the exit status.
run_apply() {
  local dir=$1 cmd=$2 input=$3 status=0
  (
    HARDWARE_CONFIG_CMD=$cmd
    export HARDWARE_CONFIG_CMD
    printf '%s' "$input" | hardware_config_apply "$dir/hardware-configuration.nix" ""
  ) >"$dir/out" 2>&1 || status=$?
  printf '%s\n' "$status"
}

# A generator that prints the canned description and succeeds. Written through a
# here-document inside the generated script, so the fixture text needs no
# escaping at any level.
good_generator() {
  make_generator "$1" "cat <<'HWEOF'
$GENERATED
HWEOF"
}

# The same, with the root filesystem pointing somewhere else, so a replacement
# can be told apart from the file it replaced.
regenerated_generator() {
  make_generator "$1" "cat <<'HWEOF'
$(printf '%s' "$GENERATED" | sed 's/deadbeef/cafebabe/')
HWEOF"
}

case_out() { cat "$1/out"; }

# --- the tracked file is a placeholder, and says so ---------------------------
#
# The sentinel is the entire mechanism that tells "nobody has run bootstrap.sh
# yet" from "this machine's real hardware description". If it were dropped from
# the tracked file, bootstrap.sh would start asking before overwriting a file
# that never described anything, and a reader could mistake the guessed disk
# labels in it for real hardware detection.

test_tracked_hardware_file_is_the_placeholder() {
  local tracked=$ROOT/hardware-configuration.nix

  [ -r "$tracked" ] || fail "the repository tracks no hardware-configuration.nix, so the flake cannot evaluate"
  hardware_config_is_placeholder "$tracked" \
    || fail "hardware-configuration.nix no longer carries the placeholder sentinel on its first line; if a real machine's file was committed, remove it - it belongs to that machine, not to this repo"
  grep -q 'fileSystems\."/"' "$tracked" \
    || fail "the placeholder declares no root filesystem, so the flake would not evaluate"

  pass "hardware: the tracked hardware-configuration.nix is the marked placeholder"
}

# --- a placeholder is replaced without asking ---------------------------------

test_placeholder_is_replaced_without_a_prompt() {
  local dir status
  dir=$(make_case placeholder)
  # Empty stdin: a prompt here would read EOF and the case would still pass by
  # accident, so the assertion below is on what was printed, not just the file.
  status=$(run_apply "$dir" "$(good_generator "$dir")" "")

  [ "$status" = 0 ] || fail "replacing the placeholder failed: $(case_out "$dir")"
  hardware_config_is_placeholder "$dir/hardware-configuration.nix" \
    && fail "the placeholder was left in place"
  assert_contains "$(cat "$dir/hardware-configuration.nix")" 'by-uuid/deadbeef' \
    "the generated description did not reach the file"
  assert_contains "$(case_out "$dir")" "still the tracked placeholder" \
    "the run did not say the file it replaced was a placeholder"
  assert_not_contains "$(case_out "$dir")" "Regenerate it" \
    "replacing a placeholder asked for confirmation"

  pass "hardware: a placeholder is replaced with the generated description, unprompted"
}

test_absent_file_is_created() {
  local dir status
  dir=$(make_case absent)
  status=$(run_apply "$dir" "$(good_generator "$dir")" "")

  [ "$status" = 0 ] || fail "creating an absent hardware file failed: $(case_out "$dir")"
  assert_contains "$(cat "$dir/hardware-configuration.nix")" 'by-uuid/deadbeef' \
    "the generated description did not reach the new file"

  pass "hardware: an absent hardware-configuration.nix is created from the generator"
}

# --- a real file is not overwritten by accident -------------------------------

test_real_file_is_kept_unless_confirmed() {
  local dir status before
  dir=$(make_case real)
  before=$(cat "$dir/hardware-configuration.nix")
  status=$(run_apply "$dir" "$(regenerated_generator "$dir")" $'n\n')

  [ "$status" = 0 ] || fail "declining to regenerate reported a failure: $(case_out "$dir")"
  [ "$(cat "$dir/hardware-configuration.nix")" = "$before" ] \
    || fail "a real hardware description was overwritten after the answer was no"
  assert_contains "$(case_out "$dir")" "already describes a real machine" \
    "the run did not say why it was asking"
  assert_contains "$(case_out "$dir")" "Keeping the existing file." \
    "the run did not report that it kept the file"

  pass "hardware: an already-generated file is kept when the answer is not yes"
}

# Enter, the answer a reader gives a prompt they did not expect, must keep the
# file. The prompt is written [y/N] and has to mean it.
test_real_file_survives_an_empty_answer() {
  local dir status before
  dir=$(make_case real)
  before=$(cat "$dir/hardware-configuration.nix")
  status=$(run_apply "$dir" "$(regenerated_generator "$dir")" $'\n')

  [ "$status" = 0 ] || fail "an empty answer reported a failure: $(case_out "$dir")"
  [ "$(cat "$dir/hardware-configuration.nix")" = "$before" ] \
    || fail "an empty answer overwrote a real hardware description"

  pass "hardware: an empty answer keeps an already-generated file"
}

test_real_file_is_replaced_when_confirmed() {
  local dir status
  dir=$(make_case real)
  status=$(run_apply "$dir" "$(regenerated_generator "$dir")" $'y\n')

  [ "$status" = 0 ] || fail "confirming a regeneration failed: $(case_out "$dir")"
  assert_contains "$(cat "$dir/hardware-configuration.nix")" 'by-uuid/cafebabe' \
    "answering yes did not put the newly generated description in place"
  pass "hardware: an already-generated file is replaced when the answer is yes"
}

# --- a bad generator never damages what is already there ----------------------

test_failing_generator_leaves_the_file_untouched() {
  local dir status before
  dir=$(make_case real)
  before=$(cat "$dir/hardware-configuration.nix")
  status=$(run_apply "$dir" "$(make_generator "$dir" 'echo boom >&2; exit 7')" $'y\n')

  [ "$status" != 0 ] || fail "a failing generator was reported as success"
  [ "$(cat "$dir/hardware-configuration.nix")" = "$before" ] \
    || fail "a failing generator truncated or replaced the existing hardware description"
  assert_contains "$(case_out "$dir")" "exit 7" \
    "the failure did not report the generator's exit status"
  assert_contains "$(case_out "$dir")" "boom" \
    "the generator's own complaint was swallowed"

  pass "hardware: a failing generator leaves the existing file untouched"
}

# A generator that succeeds and prints something useless is the more dangerous
# half: the exit status says everything is fine, and the output would build a
# system with no root filesystem.
test_generator_without_a_root_filesystem_is_refused() {
  local dir status before
  dir=$(make_case real)
  before=$(cat "$dir/hardware-configuration.nix")
  status=$(run_apply "$dir" "$(make_generator "$dir" 'echo "{ }"')" $'y\n')

  [ "$status" != 0 ] || fail "a hardware description with no root filesystem was accepted"
  [ "$(cat "$dir/hardware-configuration.nix")" = "$before" ] \
    || fail "an unusable generated description replaced a working one"
  assert_contains "$(case_out "$dir")" "no root filesystem" \
    "the refusal did not say what was missing from the generated output"

  pass "hardware: generated output with no root filesystem is refused, file unchanged"
}

# The scratch file the replacement is built in must never be left behind: it
# sits next to hardware-configuration.nix, inside the repository, where an
# untracked leftover is invisible to a flake build and confusing in git status.
test_no_scratch_file_is_left_behind() {
  local dir leftovers
  dir=$(make_case real)
  run_apply "$dir" "$(make_generator "$dir" 'echo boom >&2; exit 7')" $'y\n' >/dev/null
  run_apply "$dir" "$(make_generator "$dir" 'echo "{ }"')" $'y\n' >/dev/null
  leftovers=$(find "$dir" -maxdepth 1 -name 'hardware-configuration.nix.*' | tr '\n' ' ')
  [ -z "$leftovers" ] || fail "a refused run left scratch files behind: $leftovers"

  pass "hardware: a refused run leaves no scratch file beside the real one"
}

test_tracked_hardware_file_is_the_placeholder
test_placeholder_is_replaced_without_a_prompt
test_absent_file_is_created
test_real_file_is_kept_unless_confirmed
test_real_file_survives_an_empty_answer
test_real_file_is_replaced_when_confirmed
test_failing_generator_leaves_the_file_untouched
test_generator_without_a_root_filesystem_is_refused
test_no_scratch_file_is_left_behind

test_summary 9
